"""The Rust extension; use the ``cardgame_env`` package instead."""

import numpy as np
from numpy.typing import NDArray

class Env:
    def __init__(
        self,
        game: str,
        num_envs: int,
        seed: int,
        rules: str,
        exclude: str | None,
        controlled: list[int] | None,
        bots: list[tuple[str, float]],
        reward_scale: float,
        threads: int,
    ) -> None: ...
    @property
    def num_envs(self) -> int: ...
    @property
    def max_seats(self) -> int: ...
    def spec(self) -> str: ...
    def reset(self, seed: int | None = None) -> dict[str, NDArray[np.generic]]: ...
    def step(self, actions: NDArray[np.int64]) -> dict[str, NDArray[np.generic]]: ...
    def belief_targets(self) -> NDArray[np.int32]: ...
    def rules(self) -> list[str]: ...
    def hand_seeds(self) -> list[int]: ...

def selfplay(config: str, root: str, out: str, threads: int) -> str: ...
