name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build: [ ubuntu-stable, ubuntu-beta, ubuntu-nightly, macos-stable, windows-stable ]

        include:
          - build: ubuntu-stable
            os: ubuntu-latest
            rust: stable

          - build: ubuntu-beta
            os: ubuntu-latest
            rust: beta

          - build: ubuntu-nightly
            os: ubuntu-latest
            rust: nightly

          - build: macos-stable
            os: macos-latest
            rust: stable

          - build: windows-stable
            os: windows-latest
            rust: stable

    steps:
      - uses: actions/checkout@v2

      - name: Setting up rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Checking if it builds without errors (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path Cargo.toml